### ISSUE TITLE
HSM_user and HSM_password Parameters

### ISSUE THREAD

**Issue by derektumulak** [aws-samples/aws-cloudhsm-pkcs11-examples#26]
Can you point me to where I would find these parameters as part of the Building section in the README?

cmake .. -DHSM_USER=<user> -DHSM_PASSWORD=<password>

Thanks,
-Derek

**Comment by rday** [comment]
Sorry for the delay here. The HSM_USER and HSM_PASSWORD variables should correspond to the CU user you created during cluster setup. Does that answer the question or did I misunderstand?

**Comment by rday** [comment]
Please re-open if this problem persists!
