### ISSUE TITLE
Where do I find the parameter TRUSTED_WRAPPING_KEY_HANDLE?

### ISSUE THREAD

**Issue by derektumulak** [aws-samples/aws-cloudhsm-pkcs11-examples#39]
I believe this was added later and I'm not sure if it impacts just a subset of the examples. Can clarification be provided?

Thanks!
-Derek

**Comment by gmudambi** [comment]
TRUSTED_WRAPPING_KEY_HANDLE  was added to demonstrate how you can [use trusted keys to control key unwraps](https://docs.aws.amazon.com/cloudhsm/latest/userguide/cloudhsm_using_trusted_keys_control_key_wrap.html)

This parameter is necessary for the following samples:
https://github.com/aws-samples/aws-cloudhsm-pkcs11-examples/blob/master/src/wrapping/unwrap_with_template.c

I hope this answers your query.

_Links_:
Using Trusted Keys to Control Key Unwraps:  https://docs.aws.amazon.com/cloudhsm/latest/userguide/cloudhsm_using_trusted_keys_control_key_wrap.html

**Comment by derektumulak** [comment]
This helps. Thank you!

**Comment by rday** [comment]
Closing out as this looks resolved. Please re-open if I'm wrong!
