### ISSUE TITLE
sample to demonstrate destroying an object

### ISSUE THREAD

**Issue by nalramli** [aws-samples/aws-cloudhsm-pkcs11-examples#9]
There should be an example for pkcs11 C_DestroyObject()

**Comment by sushrb** [comment]
Sample has been added for C_DestroyObject. [Ref](https://github.com/aws-samples/aws-cloudhsm-pkcs11-examples/blob/master/src/destroy/destroy.c).

**Comment by sushrb** [comment]
Closing Issue.
